/** Shared UI patterns — backed by theme tokens in index.css */

export const chipActive = 'bg-accent-subtle text-accent'
export const chipInactive = 'text-muted-foreground hover:bg-hover hover:text-foreground'
export const inputFocus = 'focus:border-accent-border focus:ring-2 focus:ring-accent-border/30'
export const selectedRing = 'border-accent-border ring-2 ring-accent-border/30'
export const accentPairHighlight = 'border-accent-border bg-accent-subtle'
export const warningBadge = 'bg-warning-muted text-warning-foreground hover:bg-warning-hover'
export const warningPanel = 'border-warning-border text-warning-foreground'
export const warningPanelItem = 'border-warning-muted text-warning-foreground'
export const panelHeader = 'px-3 py-2 border-b border-border text-xs font-medium text-muted-foreground'
export const iconButton = 'border border-border text-muted-foreground hover:bg-hover'
export const surfaceCard = 'rounded-lg border bg-surface'
export const emptyState = 'text-sm text-muted-foreground'
export const emptyStateXs = 'text-xs text-muted-foreground'
export const sectionDivider = 'border-b border-border'
export const dropdownPanel = 'rounded border border-border bg-surface py-1 shadow-lg'
export const overlayIconButton = 'border border-border bg-surface-overlay text-muted-foreground backdrop-blur-sm hover:bg-hover'
export const textInput = 'border border-border bg-surface text-foreground outline-none placeholder:text-faint'
export const textExpandButton = 'text-muted-foreground hover:text-foreground'
